### ISSUE TITLE
panic due to concurrent read/write of map

### ISSUE THREAD

**Issue by woodsaj** [raintank/metrictank#328]
fatal error: concurrent map read and map write
memoryIdx: metricDef 12574.d91999c237ac47c39bd07d7c8270a6ff is stale. pruning it.
memoryIdx: metricDef 12574.43017b46db73a8c034e3bea3bfdb70a2 is stale. pruning it.
memoryIdx: metricDef 12574.b86f8c7efbd5c7ec1b0fb74d150e7739 is stale. pruning it.
memoryIdx: metricDef 12574.30441a19145ac9cb3f6ce1df222bbb8e is stale. pruning it.
memoryIdx: metricDef 12574.c50a3d589fc622510ef9a9897033ca42 is stale. pruning it.

goroutine 262 [running]:
runtime.throw(0xcb5000, 0x21)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8209595a0 sp=0xc820959588
runtime.mapaccess2_faststr(0x9ca040, 0xc82014e0c0, 0xc85f5651d0, 0x26, 0xc820015500, 0xc85abaa630)
        /usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc820959600 sp=0xc8209595a0
github.com/raintank/metrictank/idx/memory.(*MemoryIdx).Get(0xc820740120, 0xc85f5651d0, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/idx/memory/memory.go:222 +0x100 fp=0xc8209596f8 sp=0xc820959600
github.com/raintank/metrictank/idx/cassandra.(*CasIdx).Add(0xc820740120, 0xc85abaa5a0)
        /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/idx/cassandra/cassandra.go:158 +0x76 fp=0xc820959978 sp=0xc8209596f8
github.com/raintank/metrictank/in.In.process(0x7ff452088ae0, 0xc8510d35a0, 0x7ff452088a58, 0xc8510d35e0, 0x7ff452088a58, 0xc8510d3620, 0x7ff452088a58, 0xc8510d3660, 0x7ff452088ae0, 0xc8510d36a0, ...)

**Comment by woodsaj** [comment]
fixed in PR #329
