### ISSUE TITLE
Most recent versions of Cassandra don't support TimeWindowCompactionStrategy

### ISSUE THREAD

**Issue by replay** [raintank/metrictank#337]
I changed my `docker-compose.yml` file and removed the cassandra version specification, this makes docker download the latest version of `Cassandra` which currently is `3.7`. 
This version doesn't have the `TimeWindowCompactionStrategy` anymore. I suggest we should find an alternative compression algorithm which is supported by recent versions and then think about upgrade procedures.

```
org.apache.cassandra.exceptions.ConfigurationException: Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
	at org.apache.cassandra.utils.FBUtilities.classForName(FBUtilities.java:440) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.schema.CompactionParams.classFromName(CompactionParams.java:238) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.schema.CompactionParams.fromMap(CompactionParams.java:230) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.schema.SchemaKeyspace.createTableParamsFromRow(SchemaKeyspace.java:977) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.schema.SchemaKeyspace.fetchTable(SchemaKeyspace.java:965) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.schema.SchemaKeyspace.fetchTables(SchemaKeyspace.java:929) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspace(SchemaKeyspace.java:892) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspacesWithout(SchemaKeyspace.java:869) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.schema.SchemaKeyspace.fetchNonSystemKeyspaces(SchemaKeyspace.java:857) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:136) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:126) ~[apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:251) [apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:585) [apache-cassandra-3.7.jar:3.7]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:714) [apache-cassandra-3.7.jar:3.7]
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_102]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_102]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_102]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_102]
	at org.apache.cassandra.utils.FBUtilities.classForName(FBUtilities.java:436) ~[apache-cassandra-3.7.jar:3.7]
	... 13 common frames omitted
```

**Comment by Dieterbe** [comment]
cassandra have changed their versioning format.  from x.y.z to just x.y.    TWCS is actually a new feature that has been merged into the 3.0.X branch as of 3.0.8.   But it wasnt merged into the 3.X branch until 3.8, it's really confusing as you'd think 3.7 should be much more recent then 3.0.8 but it's not the case, which is why 3.7 doesn't have TWCS *yet* , as opposed to *not anymore* :)

looks like 3.8 was finally released a few days ago: https://groups.google.com/forum/#!topic/nosql-databases/AXrML1ekMMU

the release notes (https://git1-us-west.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=NEWS.txt;hb=refs/tags/cassandra-3.8) mention 

> TimeWindowCompactionStrategy has been added. This has proven to be a better approach
     to time series compaction and new tables should use this instead of DTCS. See
     CASSANDRA-9666 for details.

**Comment by Dieterbe** [comment]
interestingly, 3.9 also has been released already, it seems http://cassandra.apache.org/download/

so in short, we support 3.0.8, 3.8 and 3.9, but not 3.1,3.2, ...., 3.7

**Comment by replay** [comment]
Ok, that's funny. You're right, I must have gotten confused with the version numbering then. Thanks for explaining!

I'll close the ticket.
