### ISSUE TITLE
datarace in ES test on circleci

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#387]
i just saw this for the first time. must be a pretty rare one.
this was bulid https://github.com/raintank/metrictank/compare/50f73c2bb2aa...c75b171913db
```

31 total assertions

--- PASS: TestES (2.28s)
=== RUN   TestGetAddKey
MockTransport: HEAD http://localhost:9200/metrics
handler not found, returning 404MockTransport: PUT http://localhost:9200/metrics
MockTransport: POST http://localhost:9200/metrics/metric_index/_search?scroll=1m&size=1000

  When indexing metrics for orgId -1 
    Then listing metrics for OrgId -1 ✔


32 total assertions


  When indexing metrics for orgId 1 MockTransport: POST http://localhost:9200/_bulk?refresh=true
MockTransport: POST http://localhost:9200/_bulk?refresh=true
MockTransport: POST http://localhost:9200/_bulk?refresh=true

    Then listing metrics for OrgId 1 ✔


33 total assertions


  When indexing metrics for orgId 2 
    Then listing metrics for OrgId 2 ✔


34 total assertions


  When adding metricDefs with the same series name as existing metricDefs 
    then listing metrics ✔


35 total assertions

MockTransport: POST http://localhost:9200/_bulk?refresh=true
MockTransport: POST http://localhost:9200/_bulk?refresh=true
MockTransport: POST http://localhost:9200/_bulk?refresh=true
MockTransport: POST http://localhost:9200/_bulk?refresh=true
==================
WARNING: DATA RACE
Read by goroutine 75:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:115 +0x0
  github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).startDocChannel.func1()
      /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:255 +0x2f0

Previous write by goroutine 64:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:292 +0x0
  github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).shutdown()
      /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:273 +0x6e
  github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).Start.func1()
      /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:147 +0x189

Goroutine 75 (running) created at:
  github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).startDocChannel()
      /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:259 +0x42
  github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).Start.func1()
      /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:142 +0x104

Goroutine 64 (running) created at:
  github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).Start()
      /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:149 +0x99
  github.com/raintank/metrictank/idx/elasticsearch.(*EsIdx).Init()
      /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/idx/elasticsearch/elasticsearch.go:210 +0x116f
  github.com/raintank/metrictank/idx/elasticsearch.TestGetAddKey()
      /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/idx/elasticsearch/elasticsearch_test.go:147 +0x65d
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc
==================
panic: send on closed channel

goroutine 79 [running]:
panic(0x91d640, 0xc8201d5d40)
	/usr/local/go/src/runtime/panic.go:481 +0x3ff
github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).startDocChannel.func1(0xc820081540)
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:255 +0x2f1
created by github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).startDocChannel
	/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:259 +0x43
FAIL	github.com/raintank/metrictank/idx/elasticsearch	3.329s
=== RUN   TestGetAddKey

  When indexing metrics for orgId -1 
    Then listing metrics for OrgId -1 ✔


1 total assertion


  When indexing metrics for orgId 1 
    Then listing metrics for OrgId 1 ✔


2 total assertions


  When indexing metrics for orgId 2 
    Then listing metrics for OrgId 2 ✔


3 total assertions


  When adding metricDefs with the same series name as existing metricDefs 
    then listing metrics ✔


4 total assertions

--- PASS: TestGetAddKey (0.00s)
=== RUN   TestFind

  When listing root nodes 
    root nodes for orgId 1 ✔✔✔✔✔
    root nodes for orgId 2 ✔✔✔✔


13 total assertions


  When searching with GLOB ✔✔✔✔✔✔✔✔✔✔✔✔


25 total assertions
```

**Comment by woodsaj** [comment]
https://github.com/raintank/metrictank/blob/master/idx/elasticsearch/elasticsearch.go#L313-L314

retryBuf needs to be stopped before the bulkIndexer
